# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      dt_name:
        description: 'Name of the deployable target'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: "https://github.com/duality72/github-tag-action"

      - name: GitHub Tag
        uses: duality72/github-tag-action@refs/heads/master
        id: tagging
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          deployable_target: ${{ github.event.inputs.dt_name }}

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ secrets.REPO_TOKEN }}"
          environment: stage-${{ github.event.inputs.dt_name }}
          ref: ${{ steps.tagging.outputs.new_tag }}
          initial_status: success
          description: "${{ steps.tagging.outputs.new_tag }} deployed to stage"

